"""Unit tests for the mixed-package build spine."""

import pathlib
import re
import typing as typ

import pytest
import yaml
from stilyagi import model, smoke

REPOSITORY_ROOT = pathlib.Path(__file__).resolve().parents[1]
EXPECTED_SMOKE_REGION = model.Region(kind="document", text=smoke.SMOKE_SOURCE)


def _make_target(makefile: str, target: str) -> tuple[str, tuple[str, ...]]:
    """Return a Makefile target header and its recipe lines."""
    lines = makefile.splitlines()
    for line_number, line in enumerate(lines):
        if not line.startswith(f"{target}:"):
            continue
        recipe = []
        for recipe_line in lines[line_number + 1 :]:
            if recipe_line.startswith("\t"):
                recipe.append(recipe_line.strip())
                continue
            if recipe_line:
                break
        return line, tuple(recipe)
    msg = f"target {target!r} not found"
    raise AssertionError(msg)


def _normalised_lines(contents: str) -> set[str]:
    """Return stripped non-empty lines for structure-oriented file assertions."""
    return {line.strip() for line in contents.splitlines() if line.strip()}


def _workflow_document(workflow: str) -> dict[str, typ.Any]:
    """Parse a GitHub Actions workflow while preserving the `on` key as text."""
    loaded = yaml.load(workflow, Loader=yaml.BaseLoader)  # noqa: S506
    assert isinstance(loaded, dict)
    return loaded


def test_smoke_helper_exercises_the_public_rust_backed_boundary() -> None:
    """Call the same package smoke helper used by Makefile and CI."""
    document = smoke.smoke_installed_package()

    assert document.syntax is model.Syntax.MARKDOWN
    assert EXPECTED_SMOKE_REGION in document.regions


def test_smoke_helper_rejects_a_document_without_regions(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Reject payloads that do not prove Rust returned source-backed content."""

    def extract_blank_document(
        _source: str,
        syntax: model.Syntax,
    ) -> model.Document:
        return model.Document(syntax=syntax)

    monkeypatch.setattr(smoke.engine, "extract_document", extract_blank_document)

    with pytest.raises(smoke.SmokeCheckError, match="at least one region"):
        smoke.smoke_installed_package()


def test_smoke_helper_rejects_a_document_with_unexpected_syntax(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Reject payloads that do not preserve the requested syntax."""

    def extract_wrong_syntax(
        _source: str,
        _syntax: model.Syntax,
    ) -> model.Document:
        return model.Document(
            syntax=model.Syntax.PYTHON_DOCSTRING,
            regions=(model.Region(kind="document", text="# Stilyagi smoke"),),
        )

    monkeypatch.setattr(smoke.engine, "extract_document", extract_wrong_syntax)

    with pytest.raises(smoke.SmokeCheckError, match="unexpected syntax"):
        smoke.smoke_installed_package()


def test_smoke_helper_accepts_expected_region_after_other_regions(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Accept smoke payloads that include the expected region in any position."""

    def extract_expected_region_after_metadata(
        _source: str,
        syntax: model.Syntax,
    ) -> model.Document:
        return model.Document(
            syntax=syntax,
            regions=(
                model.Region(kind="metadata", text="generated by extractor"),
                EXPECTED_SMOKE_REGION,
            ),
        )

    monkeypatch.setattr(
        smoke.engine,
        "extract_document",
        extract_expected_region_after_metadata,
    )

    document = smoke.smoke_installed_package()

    assert document.regions[-1] == EXPECTED_SMOKE_REGION


def test_smoke_helper_rejects_a_document_without_expected_region(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Reject payloads that include regions but not the smoke source content."""

    def extract_unexpected_region(
        _source: str,
        syntax: model.Syntax,
    ) -> model.Document:
        return model.Document(
            syntax=syntax,
            regions=(model.Region(kind="document", text="# Unexpected smoke"),),
        )

    monkeypatch.setattr(smoke.engine, "extract_document", extract_unexpected_region)

    with pytest.raises(smoke.SmokeCheckError, match="source-backed region"):
        smoke.smoke_installed_package()


def test_smoke_main_success(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Return zero and keep stderr quiet when the smoke check succeeds."""
    calls: list[bool] = []

    def fake_smoke_installed_package() -> None:
        calls.append(True)

    monkeypatch.setattr(smoke, "smoke_installed_package", fake_smoke_installed_package)

    exit_code = smoke.main()
    captured = capsys.readouterr()

    assert exit_code == 0
    assert calls == [True]
    assert captured.err == ""


def test_smoke_main_failure(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Return one and print a prefixed SmokeCheckError message to stderr."""

    def fail_smoke_installed_package() -> None:
        raise smoke.SmokeCheckError("broken")

    monkeypatch.setattr(smoke, "smoke_installed_package", fail_smoke_installed_package)

    exit_code = smoke.main()
    captured = capsys.readouterr()

    assert exit_code == 1
    assert captured.err.startswith("Stilyagi smoke check failed: ")
    assert "broken" in captured.err


def test_makefile_keeps_build_and_release_on_the_shared_smoke_path() -> None:
    """Keep canonical local workflows wired to the same smoke boundary."""
    makefile = (REPOSITORY_ROOT / "Makefile").read_text(encoding="utf-8")
    targets = {
        name: _make_target(makefile, name)
        for name in ("build", ".venv", "smoke", "smoke-release", "markdownlint")
    }

    assert ".venv" in targets["build"][0]
    assert "$(MAKE) smoke" in targets["build"][1]
    assert "UV_VENV_CLEAR=1 $(UV_ENV) uv venv" in targets[".venv"][1]
    assert "$(CARGO_BUILD_ENV) $(UV_ENV) uv sync --group dev" in targets[".venv"][1]
    assert ".venv" in targets["smoke"][0]
    assert ".venv/bin/python -m stilyagi.smoke" in targets["smoke"][1]
    assert "release-artifact" in targets["smoke-release"][0]
    assert ".venv" in targets["smoke-release"][0]
    assert ".venv/bin/python -m venv .venv-release-smoke" in targets["smoke-release"][1]
    assert "tools-docs" in targets["markdownlint"][0]
    assert any(
        "-not -path './.venv-release-smoke/*'" in line
        for line in targets["markdownlint"][1]
    )


def test_ci_workflow_calls_the_canonical_makefile_targets() -> None:
    """Make CI exercise Makefile targets instead of duplicating build logic."""
    workflow = (REPOSITORY_ROOT / ".github" / "workflows" / "smoke.yml").read_text(
        encoding="utf-8"
    )
    parsed_workflow = _workflow_document(workflow)
    workflow_lines = _normalised_lines(workflow)
    run_commands = {
        line.removeprefix("run:").strip()
        for line in workflow_lines
        if line.startswith("run:")
    }

    assert {
        "make check-fmt",
        "make markdownlint",
        "make nixie",
        "make lint",
        "make test",
        "make release",
    }.issubset(run_commands)
    push_branches = parsed_workflow["on"]["push"]["branches"]
    assert "pull_request:" in workflow_lines
    assert "main" in push_branches
    assert re.search(r"python-version:\s*[\"']?3\.x[\"']?", workflow) is not None
    assert "mdformat-all" not in workflow
    assert "uv tool install nixie-cli==1.0.0" in workflow_lines
    assert "--git https://github.com/leynos/whitaker \\" in workflow_lines
    assert "whitaker-installer --cranelift" in workflow_lines
