[package]
name = "stilyagi-extract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
markdown.workspace = true
stilyagi-ir = { path = "../stilyagi-ir" }
stilyagi-markdown = { path = "../stilyagi-markdown" }
stilyagi-tree-sitter = { path = "../stilyagi-tree-sitter" }

[dev-dependencies]
insta.workspace = true
rstest.workspace = true
rstest-bdd.workspace = true
rstest-bdd-macros.workspace = true
stilyagi-test-support = { path = "../stilyagi-test-support" }

[lints]
workspace = true
