#!/usr/bin/env -S uv run python
# /// script
# requires-python = ">=3.13"
# dependencies = []
# ///
"""Generate ``typos.toml`` enforcing en-GB-oxendict (Oxford) spelling.

The ``en-gb`` locale in ``typos`` corrects American spellings to British
ones, but it prefers the ``-ise`` family and rejects Oxford ``-ize`` forms.
For each curated stem this script therefore emits:

- an identity entry accepting each Oxford ``-ize`` inflection that the
  locale would otherwise "correct" to ``-ise``, and
- an ``-ise`` to ``-ize`` correction for the same inflection, which the
  locale accepts silently.

Stems taking ``-yse`` (analyse, paralyse, catalyse) are deliberately
absent: Oxford retains ``-yse`` and the locale already enforces it.
Genuinely ``-ise``-only words (advise, revise, exercise, supervise, and so
on) are excluded from the stem list, so they remain accepted.

Examples
--------
Run from the repository root to rewrite ``typos.toml`` in place:

>>> # uv run scripts/generate_typos_config.py  # doctest: +SKIP

The stem ``organ`` produces entries such as ``organised = "organized"``
and ``organized = "organized"`` for every suffix pair.
"""

from __future__ import annotations

from pathlib import Path

#: Word stems that take Oxford ``-ize``; each stem is the word up to but
#: not including the ``-ise``/``-ize`` suffix. Curated for vocabulary
#: plausible in software documentation; extend as new words appear.
STEMS = (
    "anonym",
    "apolog",
    "author",
    "canonical",
    "capital",
    "categor",
    "central",
    "character",
    "civil",
    "colon",
    "container",
    "critic",
    "custom",
    "decentral",
    "denormal",
    "deserial",
    "destabil",
    "emphas",
    "energ",
    "equal",
    "factor",
    "familiar",
    "final",
    "formal",
    "general",
    "global",
    "harmon",
    "hypothes",
    "ideal",
    "initial",
    "internal",
    "international",
    "item",
    "jeopard",
    "legitim",
    "linear",
    "local",
    "material",
    "maxim",
    "mechan",
    "memor",
    "miniatur",
    "minim",
    "mobil",
    "modern",
    "modular",
    "monet",
    "neutral",
    "normal",
    "operational",
    "optim",
    "organ",
    "parameter",
    "parametr",
    "penal",
    "personal",
    "plural",
    "priorit",
    "public",
    "quant",
    "random",
    "rational",
    "real",
    "recogn",
    "regular",
    "reinitial",
    "reorgan",
    "sanit",
    "scrutin",
    "serial",
    "singular",
    "special",
    "stabil",
    "standard",
    "styl",
    "subsid",
    "summar",
    "symbol",
    "synchron",
    "synthes",
    "systemat",
    "theor",
    "token",
    "trivial",
    "unauthor",
    "uncategor",
    "uninitial",
    "unoptim",
    "unrecogn",
    "unsynchron",
    "util",
    "vector",
    "virtual",
    "visual",
)

#: Words accepted verbatim: libraries, suffix fragments quoted in prose,
#: hyphenated prefixes split by the tokenizer, and non-English example text.
EXTRA_ACCEPTED_WORDS = (
    "astroid",  # the Python abstract-syntax-tree library used by Pylint
    "yse",  # the "-yse" suffix quoted in spelling guidance
    "mis",  # hyphenated prefix, as in "mis-applied"
    "inventario",  # Spanish Gherkin example in the rstest-bdd users' guide
)

#: (British ``-ise`` inflection, Oxford ``-ize`` inflection) suffix pairs.
SUFFIX_PAIRS = (
    ("ise", "ize"),
    ("ises", "izes"),
    ("ised", "ized"),
    ("ising", "izing"),
    ("iser", "izer"),
    ("isers", "izers"),
    ("isable", "izable"),
    ("isation", "ization"),
    ("isations", "izations"),
)

HEADER = """\
# typos configuration enforcing en-GB-oxendict (Oxford spelling).
#
# Generated by scripts/generate_typos_config.py; regenerate rather than
# editing entries by hand:
#
#     uv run scripts/generate_typos_config.py
#
# The en-gb locale corrects American spellings (color -> colour,
# behavior -> behaviour, analyzed -> analysed) but prefers -ise over the
# Oxford -ize. The extend-words table below restores Oxford spelling:
# identity entries accept -ize inflections, and -ise entries are
# corrected to -ize.

[files]
extend-exclude = [
    ".git",
    ".venv",
    ".venv-release-smoke",
    ".uv-cache",
    ".uv-tools",
    "target",
    "crates/stilyagi-pyext/target",
    "dist",
    "uv.lock",
    "Cargo.lock",
    "tests/fixtures",
]

[default]
locale = "en-gb"
extend-ignore-re = [
    # Inline code spans and fenced code blocks quote APIs and identifiers,
    # which keep their upstream spelling (for example `color`, `flavor`).
    '`[^`\\n]+`',
    '(?s)```.*?```',
    # Tool and Makefile target names that keep their upstream spelling
    # even when they appear outside code spans.
    'rust-analyzer',
    'release-artifact',
    # ExecPlan template heading.
    '## Artifacts and notes',
    # Verbatim citation title.
    'Center \\| Microsoft Learn',
]

[default.extend-words]
"""


def render_config() -> str:
    """Render the full ``typos.toml`` document as a string.

    Returns
    -------
    str
        The configuration text, ending with a trailing newline.

    Examples
    --------
    >>> 'organised = "organized"' in render_config()
    True
    """
    lines = [HEADER.rstrip("\n")]
    lines.extend(f'{word} = "{word}"' for word in EXTRA_ACCEPTED_WORDS)
    lines.extend(
        entry
        for stem in sorted(STEMS)
        for ise, ize in SUFFIX_PAIRS
        for entry in (
            f'{stem}{ise} = "{stem}{ize}"',
            f'{stem}{ize} = "{stem}{ize}"',
        )
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write ``typos.toml`` beside this script's repository root.

    Examples
    --------
    >>> main()  # doctest: +SKIP
    """
    output = Path(__file__).resolve().parent.parent / "typos.toml"
    output.write_text(render_config(), encoding="utf-8")


if __name__ == "__main__":
    main()
