[package]
name = "stilyagi-test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
stilyagi-ir = { path = "../stilyagi-ir" }
stilyagi-test-fixtures = { path = "../stilyagi-test-fixtures" }
stilyagi-tree-sitter = { path = "../stilyagi-tree-sitter" }

[dev-dependencies]
insta.workspace = true
proptest = "1"
rstest.workspace = true

[lints]
workspace = true
